"use client";
/* eslint-disable jsx-a11y/alt-text -- React PDF Image is not an HTML image. */
import Link from "next/link";
import { useState } from "react";
import { Document, Page, Text, View, Image, StyleSheet, PDFViewer, PDFDownloadLink, pdf } from "@react-pdf/renderer";
import type { Customer, Quote, Settings } from "@/lib/types";
import { gbp, ukDate, whatsappUrl } from "@/lib/format";
import { compatibleItems, safePdfFilename } from "@/lib/quote-pdf";
import { Download, Printer, Pencil, X, Mail, MessageCircle, Share2, FileText } from "lucide-react";

type Data={quote:Quote;customer:Customer;settings:Settings;logoUrl?:string|null};
const s=StyleSheet.create({page:{padding:40,paddingBottom:55,fontFamily:"Helvetica",fontSize:9,color:"#24322f"},header:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",minHeight:58,paddingBottom:16,borderBottom:"2 solid #0d766e"},logo:{width:130,height:58,objectFit:"contain",objectPosition:"left center"},brand:{fontSize:22,fontWeight:700,color:"#102522"},contact:{alignItems:"flex-end",maxWidth:270},muted:{color:"#64716d",lineHeight:1.4},title:{fontSize:26,fontWeight:700,color:"#102522",marginTop:24},meta:{flexDirection:"row",justifyContent:"space-between",marginTop:8},columns:{flexDirection:"row",gap:30,marginTop:22},column:{flex:1},heading:{fontSize:8,fontWeight:700,color:"#0d766e",textTransform:"uppercase",letterSpacing:1,marginBottom:6},body:{fontSize:10,lineHeight:1.5},job:{marginTop:22,padding:14,backgroundColor:"#f0f7f5",borderRadius:5},table:{marginTop:20},row:{flexDirection:"row",borderBottom:"1 solid #d9e1de",paddingVertical:8},desc:{width:"52%"},qty:{width:"12%",textAlign:"right"},price:{width:"18%",textAlign:"right"},total:{width:"18%",textAlign:"right",fontWeight:700},thead:{backgroundColor:"#102522",color:"white",paddingHorizontal:8},cell:{paddingHorizontal:8},totals:{marginTop:15,marginLeft:"52%",padding:12,backgroundColor:"#f7f8f7"},totalLine:{flexDirection:"row",justifyContent:"space-between",paddingVertical:3},grand:{marginTop:6,paddingTop:8,borderTop:"1 solid #0d766e",fontSize:14,fontWeight:700,color:"#0d766e"},section:{marginTop:18},footer:{position:"absolute",bottom:22,left:40,right:40,borderTop:"1 solid #d9e1de",paddingTop:7,textAlign:"center",fontSize:8,color:"#64716d"}});
const premium=StyleSheet.create({header:{marginTop:-40,marginLeft:-40,marginRight:-40,minHeight:145,paddingTop:22,paddingBottom:22,paddingHorizontal:40,backgroundColor:"#102522",borderBottom:"6 solid #f4b942"},logo:{width:190,height:105,objectFit:"contain",objectPosition:"left center"},contactText:{color:"#ffffff",fontSize:10,lineHeight:1.6},title:{marginTop:28,color:"#102522",fontSize:29},meta:{marginTop:12,paddingVertical:12,paddingHorizontal:14,backgroundColor:"#eef7f4",borderLeft:"4 solid #0d766e"},columns:{marginTop:18,padding:16,backgroundColor:"#ffffff",border:"1 solid #dbe2df",borderRadius:6},table:{marginTop:22,border:"1 solid #dbe2df",borderRadius:4},totals:{backgroundColor:"#102522",color:"#ffffff",padding:16,borderRadius:6},grand:{color:"#f4b942",borderTop:"1 solid #f4b942",fontSize:16},section:{padding:13,backgroundColor:"#f7faf8",borderLeft:"3 solid #0d766e"}});

function QuoteDocument({data}:{data:Data}){
 const{quote,customer,settings,logoUrl}=data;
 const displayPhone=settings.telephone.replace(/^\+44\s?/,"0");
 const items=compatibleItems(quote.quote_items?.map(x=>({description:x.description,quantity:Number(x.quantity),unitPricePence:Number(x.unit_price),sortOrder:x.sort_order})),quote.value_pence,quote.job_description);
 const subtotal=quote.subtotal||items.reduce((n,x)=>n+Math.round(x.quantity*x.unitPricePence),0),final=quote.final_total||quote.value_pence;
 return <Document title={`Quotation ${quote.quote_number||""}`} author={settings.business_name}><Page size="A4" style={s.page} wrap>
  <View style={[s.header,premium.header]} fixed>{logoUrl?<Image src={logoUrl} style={[s.logo,premium.logo]}/>:<Text style={[s.brand,{color:"#ffffff"}]}>{settings.business_name||"QUOTATION"}</Text>}<View style={s.contact}><Text style={premium.contactText}>{displayPhone}</Text><Text style={premium.contactText}>{settings.business_email}</Text><Text style={premium.contactText}>{settings.business_address}</Text></View></View>
  <Text style={[s.title,premium.title]}>QUOTATION</Text><View style={[s.meta,premium.meta]}><Text>Quote: {quote.quote_number||"Pending"}</Text><Text>Date: {ukDate(quote.quote_date)}</Text><Text>Valid until: {ukDate(quote.expiry_date)}</Text></View>
  <View style={[s.columns,premium.columns]}><View style={s.column}><Text style={s.heading}>From</Text><Text style={s.body}>{settings.business_name||"Business details not set"}</Text><Text style={s.body}>{settings.business_address}</Text><Text style={s.body}>{settings.business_email}</Text><Text style={s.body}>{displayPhone}</Text>{settings.vat_registered&&<Text style={s.body}>VAT: {settings.vat_number}</Text>}</View><View style={s.column}><Text style={s.heading}>Prepared for</Text><Text style={s.body}>{customer.name}</Text><Text style={s.body}>{customer.address||"Address not supplied"}</Text><Text style={s.body}>{customer.email||""}</Text><Text style={s.body}>{customer.mobile||""}</Text></View></View>
  <View style={[s.table,premium.table]}><View style={[s.row,s.thead]} fixed><Text style={[s.desc,s.cell]}>Description</Text><Text style={[s.qty,s.cell]}>Qty</Text><Text style={[s.price,s.cell]}>Unit price</Text><Text style={[s.total,s.cell]}>Total</Text></View>{items.map((item,i)=><View style={s.row} key={i} wrap={false}><Text style={[s.desc,s.cell]}>{item.description}</Text><Text style={[s.qty,s.cell]}>{item.quantity}</Text><Text style={[s.price,s.cell]}>{gbp(item.unitPricePence)}</Text><Text style={[s.total,s.cell]}>{gbp(Math.round(item.quantity*item.unitPricePence))}</Text></View>)}</View>
  <View style={[s.totals,premium.totals]} wrap={false}><View style={s.totalLine}><Text>Subtotal</Text><Text>{gbp(subtotal)}</Text></View>{Number(quote.discount_value)>0&&<View style={s.totalLine}><Text>Discount</Text><Text>{quote.discount_type==="percentage"?`${quote.discount_value}%`:gbp(Number(quote.discount_value)*100)}</Text></View>}{quote.vat_enabled&&<View style={s.totalLine}><Text>VAT ({quote.vat_rate}%)</Text><Text>{gbp(quote.vat_amount)}</Text></View>}<View style={[s.totalLine,s.grand,premium.grand]}><Text>TOTAL</Text><Text>{gbp(final)}</Text></View></View>
  {quote.notes&&<View style={[s.section,premium.section]}><Text style={s.heading}>Notes</Text><Text style={s.body}>{quote.notes}</Text></View>}<View style={[s.section,premium.section]}><Text style={s.heading}>Payment terms</Text><Text style={s.body}>{quote.payment_terms||settings.default_payment_terms}</Text></View><View style={[s.section,premium.section]}><Text style={s.heading}>Terms and conditions</Text><Text style={s.body}>{quote.terms_and_conditions||settings.default_terms_and_conditions}</Text></View>
  <Text style={s.footer} fixed>{settings.business_name} · {displayPhone} · {settings.business_email} · {settings.business_address}</Text>
 </Page></Document>;
}

export default function QuotePdfActions({data}:{data:Data}){
 const[open,setOpen]=useState(false);const q=data.quote,c=data.customer,b=data.settings,valid=!!c?.name&&!!q.job_description&&q.value_pence>0;const filename=safePdfFilename(q.quote_number||"Draft",c?.name||"Customer");const message=`Hi ${c?.name}, your quotation ${q.quote_number||""} for ${gbp(q.final_total||q.value_pence)} is ready and valid until ${ukDate(q.expiry_date)}.`;const subject=`Quotation ${q.quote_number||""} from ${b.business_name||"Quote-Chaser"}`;const body=`Hi ${c?.name},\n\nPlease find your quotation for ${q.job_description}.\n\nQuote number: ${q.quote_number}\nTotal: ${gbp(q.final_total||q.value_pence)}\nValid until: ${ukDate(q.expiry_date)}\n\nPlease contact us if you have any questions.\n\nKind regards,\n${b.business_name}`;
 async function share(){try{const blob=await pdf(<QuoteDocument data={data}/>).toBlob(),file=new File([blob],filename,{type:"application/pdf"});if(navigator.share&&navigator.canShare?.({files:[file]}))await navigator.share({title:subject,text:message,files:[file]});else if(navigator.share)await navigator.share({title:subject,text:message});else throw new Error()}catch{alert("Sharing is not available here. Download the PDF and share it from your device instead.")}}
 return <>{!valid?<p className="rounded-xl bg-amber-50 p-4 font-bold text-amber-900">Add a customer, job description and quote value before creating a PDF.</p>:<button className="btn btn-primary" onClick={()=>setOpen(true)}><FileText size={18}/>Create PDF Quote</button>}{open&&<div className="fixed inset-0 z-50 flex flex-col bg-slate-950/80 p-2 backdrop-blur sm:p-5"><div className="mx-auto flex w-full max-w-6xl flex-wrap items-center gap-2 rounded-t-2xl bg-white p-3"><PDFDownloadLink document={<QuoteDocument data={data}/>} fileName={filename} className="btn btn-primary">{({loading})=><><Download size={17}/>{loading?"Preparing…":"Download PDF"}</>}</PDFDownloadLink><button className="btn btn-secondary" onClick={()=>window.print()}><Printer size={17}/>Print</button><Link className="btn btn-secondary" href={`/quotes/${q.id}/edit`}><Pencil size={17}/>Edit quote</Link>{c.mobile&&<a className="btn btn-secondary" href={whatsappUrl(c.mobile,message)} target="_blank" rel="noreferrer"><MessageCircle size={17}/>WhatsApp</a>}{c.email&&<a className="btn btn-secondary" href={`mailto:${encodeURIComponent(c.email)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`}><Mail size={17}/>Email</a>}<button className="btn btn-secondary" onClick={share}><Share2 size={17}/>Share</button><button className="btn btn-secondary ml-auto" onClick={()=>setOpen(false)}><X size={18}/>Close</button></div><div className="mx-auto min-h-0 w-full max-w-6xl flex-1 overflow-hidden rounded-b-2xl bg-slate-200"><PDFViewer width="100%" height="100%" showToolbar={false}><QuoteDocument data={data}/></PDFViewer></div></div>}</>;
}
