import type { Metadata } from "next";
import Link from "next/link";
import { AlertTriangle, Download, Mail, Trash2 } from "lucide-react";
import { LegalPage, SUPPORT_EMAIL } from "@/components/legal-page";
import { LegalSection } from "@/components/legal-section";

export const metadata: Metadata = { title: "Delete Your Account", description: "How to request deletion of a Quote-Chaser account and its stored customer and quote data." };

export default function AccountDeletion() { const subject = encodeURIComponent("Delete my Quote-Chaser account"); const body = encodeURIComponent("Please delete my Quote-Chaser account and the data linked to it.\n\nAccount email: \nBusiness name: \n\nI understand that deletion is permanent."); return <LegalPage eyebrow="Account controls" title="Delete your Quote-Chaser account" summary="You can request permanent deletion of your account, customer records, quotes, follow-up history and settings.">
  <div className="rounded-2xl border border-rose-200 bg-rose-50 p-5 sm:p-6"><AlertTriangle className="text-rose-700" size={30}/><h2 className="mt-4 text-2xl text-rose-950">Deletion cannot be undone</h2><p className="mt-2 leading-7 text-rose-950">Once completed, you will lose access to stored customers, quotations, follow-up history, reports, settings and generated quote information.</p></div>
  <LegalSection title="Before you request deletion"><p className="flex items-start gap-3"><Download className="mt-1 shrink-0 text-teal-700" size={22}/>Download any PDF quotes or copy records that you are legally required to keep. Deleting Quote-Chaser data does not remove copies you previously downloaded, emailed, printed or sent through another service.</p><p>Settle any outstanding subscription charges and cancel active billing where applicable.</p></LegalSection>
  <LegalSection title="How to request deletion"><ol><li>Email us from the address registered to your Quote-Chaser account.</li><li>Use the subject <strong>Delete my Quote-Chaser account</strong>.</li><li>Include your account email and business name. Do not send your password.</li><li>We will verify the request and confirm when deletion is complete.</li></ol><a className="btn btn-danger mt-5" href={`mailto:${SUPPORT_EMAIL}?subject=${subject}&body=${body}`}><Trash2 size={18}/> Request account deletion</a></LegalSection>
  <LegalSection title="What we delete"><p>We delete or irreversibly anonymise the live account profile, user settings, customers, quotes and follow-up history associated with the account. Authentication access is removed so the account can no longer be used.</p></LegalSection>
  <LegalSection title="Timing and information we may retain"><p>We aim to complete verified requests without undue delay and normally within one month. Limited information may be retained where required for tax, accounting, fraud prevention, security, dispute resolution or another legal obligation. Residual encrypted backup copies expire through normal backup rotation and are not used for ordinary business purposes.</p></LegalSection>
  <LegalSection title="Deleting individual records instead"><p>If you want to keep your account, customers and quotes can be deleted individually from the relevant pages. Contact <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a> if you need help or read our <Link href="/privacy">Privacy Policy</Link>.</p></LegalSection>
  <p className="flex items-center gap-2 rounded-xl bg-slate-100 p-4"><Mail size={19}/><strong>Requests:</strong> <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a></p>
</LegalPage>; }
